{"name":"force_fail_testcase:", "desc":"Fails a testcase for whatever reasons", "ordinal":"1", "abort":"0", "fail_type":"Error", "execute":"python tauto.py step1.yaml", "id":"0"}